apiVersion: v1
kind: Service
metadata:
  name: grok-exporter
  labels:
    sidecar: grok-exporter
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 9144
      port: 9144
  selector:
    sidecar: grok-exporter