apiVersion: v1
kind: Service
metadata:
  name: spring-logging-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    sidecar: spring-logging-app